# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('publisher', models.CharField(max_length=200, verbose_name='publisher')),
                ('uploader', models.CharField(max_length=200, verbose_name='uploader')),
                ('classification', models.CharField(max_length=200, verbose_name='classification')),
                ('isbn', models.CharField(max_length=200, verbose_name='isbn')),
                ('novelty', models.FloatField(max_length=200, verbose_name='novelty')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('image', models.ImageField(max_length=200, upload_to='', verbose_name='image')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('publication_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
